#!/bin/bash

KEY=$1
if [ `echo $1 | wc -m` != 33 ]; then
        echo "Please specify a 32 byte string without white space to use as an AES key for auto-ossec client/server communication."
        echo "This new secret will be set in the auto_ossec.py and auto_server.py scripts in the current directory if present."
        exit
fi

sed -i 's/\(\s*\)secret = .*/\1secret = "'$KEY'"/' ./auto_ossec.py ./auto_server.py

grep "secret ="  ./auto_ossec.py ./auto_server.py

echo "If you are using auto_ossec.exe then make sure to rebuild it against the modified auto_ossec.py."

